using Microsoft.EntityFrameworkCore;
using TooL82.Web.Data;
using TooL82.Web.Models.Entities;
using TooL82.Web.Services.Implementations;
using TooL82.Web.Services.Interfaces;

var builder = WebApplication.CreateBuilder(args);

// Add DbContext - SQL Server
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString!));

// Add Session
builder.Services.AddDistributedMemoryCache();
builder.Services.AddSession(options =>
{
    options.IdleTimeout = TimeSpan.FromMinutes(30);
    options.Cookie.HttpOnly = true;
    options.Cookie.IsEssential = true;
});

// Add Services (DI)
builder.Services.AddScoped<IMemberService, MemberService>();
builder.Services.AddScoped<IProductService, ProductService>();
builder.Services.AddScoped<ISaleService, SaleService>();
builder.Services.AddScoped<IPurchaseService, PurchaseService>();

// Add MVC
builder.Services.AddControllersWithViews();

var app = builder.Build();

// Initialize database and seed sample data
using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    context.Database.EnsureCreated();
    SeedData(context);
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();

app.UseSession();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run();

// Sample data seeding with original data
void SeedData(ApplicationDbContext context)
{
    if (context.Members.Any()) return;

    // Hash password for seed data
    string HashPassword(string password) => BCrypt.Net.BCrypt.HashPassword(password);

    // Add original members (Mno will be auto-generated by SQL Server)
    var members = new List<Member>
    {
        new() { Name = "선민이", UserId = "sunminnie", Passwd = HashPassword("1234"), Email = "dhn9@dam.net", SellerYn = "Y", RegDate = DateTime.Now },
        new() { Name = "희망변호사", UserId = "lawhope", Passwd = HashPassword("1234"), Email = "jhs1111@homail.com", SellerYn = "Y", RegDate = DateTime.Now },
        new() { Name = "구매자1", UserId = "buyer1", Passwd = HashPassword("1234"), Email = "buyer1@test.com", SellerYn = "N", RegDate = DateTime.Now },
        new() { Name = "구매자2", UserId = "buyer2", Passwd = HashPassword("1234"), Email = "buyer2@test.com", SellerYn = "N", RegDate = DateTime.Now },
        new() { Name = "조포에바", UserId = "joh4eva", Passwd = HashPassword("1234"), Email = "sjlee@natee.com", SellerYn = "Y", RegDate = DateTime.Now },
        new() { Name = "구매자3", UserId = "buyer3", Passwd = HashPassword("1234"), Email = "buyer3@test.com", SellerYn = "N", RegDate = DateTime.Now },
        new() { Name = "구매자4", UserId = "buyer4", Passwd = HashPassword("1234"), Email = "buyer4@test.com", SellerYn = "N", RegDate = DateTime.Now },
        new() { Name = "구매자5", UserId = "buyer5", Passwd = HashPassword("1234"), Email = "buyer5@test.com", SellerYn = "N", RegDate = DateTime.Now },
        new() { Name = "황금막내", UserId = "goldenmaknae", Passwd = HashPassword("1234"), Email = "worldno1@bts.co.kr", SellerYn = "Y", RegDate = DateTime.Now },
        new() { Name = "구매자6", UserId = "buyer6", Passwd = HashPassword("1234"), Email = "buyer6@test.com", SellerYn = "N", RegDate = DateTime.Now },
        new() { Name = "구매자7", UserId = "buyer7", Passwd = HashPassword("1234"), Email = "buyer7@test.com", SellerYn = "N", RegDate = DateTime.Now },
        new() { Name = "제이호호호", UserId = "jayhohoho", Passwd = HashPassword("1234"), Email = "wwhandsome@bts.co.kr", SellerYn = "Y", RegDate = DateTime.Now },
        new() { Name = "구매자8", UserId = "buyer8", Passwd = HashPassword("1234"), Email = "buyer8@test.com", SellerYn = "N", RegDate = DateTime.Now },
        new() { Name = "구매자9", UserId = "buyer9", Passwd = HashPassword("1234"), Email = "buyer9@test.com", SellerYn = "N", RegDate = DateTime.Now },
        new() { Name = "꽃송화", UserId = "flowersonghwa", Passwd = HashPassword("1234"), Email = "jennie@blackpink.com", SellerYn = "Y", RegDate = DateTime.Now },
    };
    context.Members.AddRange(members);
    context.SaveChanges();

    // Add original products (48 items)
    var products = new List<Product>
    {
        // Music (m)
        new() { UserId = "sunminnie", Category = "m", Title = "Finale Version 26", Party = 47, CPartied = 23, Email = "dhn9@dam.net", SDate = DateTime.Parse("2021-05-25"), EDate = DateTime.Now.AddDays(30), OPrice = 680000, SPrice = 400000, Contents = "음악 만들자!", SellStat = 0 },
        new() { UserId = "lawhope", Category = "m", Title = "Logic Pro x", Party = 56, CPartied = 17, Email = "jhs1111@homail.com", SDate = DateTime.Parse("2021-07-15"), EDate = DateTime.Now.AddDays(14), OPrice = 230000, SPrice = 150000, Contents = "음악 만들자!", SellStat = 0 },
        new() { UserId = "joh4eva", Category = "m", Title = "FL studio", Party = 55, CPartied = 55, Email = "sjlee@natee.com", SDate = DateTime.Parse("2021-04-09"), EDate = DateTime.Now.AddDays(-10), OPrice = 230000, SPrice = 172000, Contents = "음악 만들자!", SellStat = 1 },
        new() { UserId = "goldenmaknae", Category = "m", Title = "Propellerhead Reason", Party = 39, CPartied = 27, Email = "worldno1@bts.co.kr", SDate = DateTime.Parse("2021-07-06"), EDate = DateTime.Now.AddDays(20), OPrice = 450000, SPrice = 197000, Contents = "음악 만들자!", SellStat = 0 },
        new() { UserId = "jayhohoho", Category = "m", Title = "Ableton Live", Party = 52, CPartied = 52, Email = "wwhandsome@bts.co.kr", SDate = DateTime.Parse("2021-03-23"), EDate = DateTime.Now.AddDays(-5), OPrice = 230000, SPrice = 170000, Contents = "음악 만들자!", SellStat = 1 },
        new() { UserId = "flowersonghwa", Category = "m", Title = "Cockos Reaper", Party = 15, CPartied = 14, Email = "jennie@blackpink.com", SDate = DateTime.Parse("2021-07-02"), EDate = DateTime.Now.AddDays(7), OPrice = 260000, SPrice = 160000, Contents = "음악 만들자!", SellStat = 0 },
        new() { UserId = "sunminnie", Category = "m", Title = "PreSonus Studio", Party = 51, CPartied = 51, Email = "rosie@blackpink.com", SDate = DateTime.Parse("2020-12-06"), EDate = DateTime.Now.AddDays(-30), OPrice = 480000, SPrice = 240000, Contents = "음악 만들자!", SellStat = 1 },
        new() { UserId = "lawhope", Category = "m", Title = "Acid Pro", Party = 33, CPartied = 33, Email = "tan@madmonster.com", SDate = DateTime.Parse("2021-01-30"), EDate = DateTime.Now.AddDays(-20), OPrice = 230000, SPrice = 154000, Contents = "음악 만들자!", SellStat = 1 },
        new() { UserId = "joh4eva", Category = "m", Title = "Bitwig Studio", Party = 37, CPartied = 37, Email = "ikjoonlee@yoolje.com", SDate = DateTime.Parse("2020-12-16"), EDate = DateTime.Now.AddDays(-25), OPrice = 340000, SPrice = 200000, Contents = "음악 만들자!", SellStat = 1 },
        new() { UserId = "goldenmaknae", Category = "m", Title = "Acoustica Mixcraft", Party = 24, CPartied = 24, Email = "dhn9@dam.net", SDate = DateTime.Parse("2021-02-11"), EDate = DateTime.Now.AddDays(-15), OPrice = 170000, SPrice = 127000, Contents = "음악 만들자!", SellStat = 1 },
        new() { UserId = "jayhohoho", Category = "m", Title = "Loopcloud", Party = 16, CPartied = 16, Email = "jhs1111@homail.com", SDate = DateTime.Parse("2021-03-25"), EDate = DateTime.Now.AddDays(-12), OPrice = 14000, SPrice = 9000, Contents = "음악 만들자!", SellStat = 1 },
        new() { UserId = "flowersonghwa", Category = "m", Title = "Pro-tools", Party = 51, CPartied = 51, Email = "sjlee@natee.com", SDate = DateTime.Parse("2021-04-26"), EDate = DateTime.Now.AddDays(-8), OPrice = 90000, SPrice = 73800, Contents = "음악 만들자!", SellStat = 1 },

        // Video (v)
        new() { UserId = "sunminnie", Category = "v", Title = "Final Cut Pro X", Party = 27, CPartied = 27, Email = "worldno1@bts.co.kr", SDate = DateTime.Parse("2021-03-18"), EDate = DateTime.Now.AddDays(-18), OPrice = 369000, SPrice = 170000, Contents = "영상 만들자!", SellStat = 1 },
        new() { UserId = "lawhope", Category = "v", Title = "Filmora Pro", Party = 39, CPartied = 23, Email = "wwhandsome@bts.co.kr", SDate = DateTime.Parse("2021-06-21"), EDate = DateTime.Now.AddDays(10), OPrice = 170000, SPrice = 127500, Contents = "영상 만들자!", SellStat = 0 },
        new() { UserId = "joh4eva", Category = "v", Title = "EDIUS", Party = 38, CPartied = 36, Email = "jennie@blackpink.com", SDate = DateTime.Parse("2021-06-26"), EDate = DateTime.Now.AddDays(5), OPrice = 570000, SPrice = 245100, Contents = "영상 만들자!", SellStat = 0 },
        new() { UserId = "goldenmaknae", Category = "v", Title = "Avid Media Composer", Party = 42, CPartied = 42, Email = "rosie@blackpink.com", SDate = DateTime.Parse("2021-04-13"), EDate = DateTime.Now.AddDays(-14), OPrice = 28000, SPrice = 15000, Contents = "영상 만들자!", SellStat = 1 },
        new() { UserId = "jayhohoho", Category = "v", Title = "HitFilm Pro", Party = 57, CPartied = 57, Email = "tan@madmonster.com", SDate = DateTime.Parse("2021-02-12"), EDate = DateTime.Now.AddDays(-22), OPrice = 390000, SPrice = 137000, Contents = "영상 만들자!", SellStat = 1 },
        new() { UserId = "flowersonghwa", Category = "v", Title = "Lightworks", Party = 28, CPartied = 28, Email = "ikjoonlee@yoolje.com", SDate = DateTime.Parse("2021-03-11"), EDate = DateTime.Now.AddDays(-16), OPrice = 28000, SPrice = 13000, Contents = "영상 만들자!", SellStat = 1 },
        new() { UserId = "sunminnie", Category = "v", Title = "Magix Video Pro X", Party = 23, CPartied = 23, Email = "dhn9@dam.net", SDate = DateTime.Parse("2021-05-27"), EDate = DateTime.Now.AddDays(-6), OPrice = 450000, SPrice = 247500, Contents = "영상 만들자!", SellStat = 1 },
        new() { UserId = "lawhope", Category = "v", Title = "cyberLink PowerDirector365", Party = 30, CPartied = 30, Email = "jhs1111@homail.com", SDate = DateTime.Parse("2021-03-31"), EDate = DateTime.Now.AddDays(-11), OPrice = 5000, SPrice = 2500, Contents = "영상 만들자!", SellStat = 1 },

        // Game (g)
        new() { UserId = "joh4eva", Category = "g", Title = "Monster Hunter Rise", Party = 42, CPartied = 38, Email = "sjlee@natee.com", SDate = DateTime.Parse("2021-06-27"), EDate = DateTime.Now.AddDays(3), OPrice = 76800, SPrice = 45000, Contents = "게임하자!", SellStat = 0 },
        new() { UserId = "goldenmaknae", Category = "g", Title = "It Takes Two", Party = 50, CPartied = 50, Email = "worldno1@bts.co.kr", SDate = DateTime.Parse("2021-04-14"), EDate = DateTime.Now.AddDays(-13), OPrice = 46700, SPrice = 16000, Contents = "게임하자!", SellStat = 1 },
        new() { UserId = "jayhohoho", Category = "g", Title = "Dying Light Platinum Edition", Party = 28, CPartied = 28, Email = "wwhandsome@bts.co.kr", SDate = DateTime.Parse("2021-03-05"), EDate = DateTime.Now.AddDays(-17), OPrice = 109900, SPrice = 58000, Contents = "게임하자!", SellStat = 1 },
        new() { UserId = "flowersonghwa", Category = "g", Title = "미토피아(Miitopia)", Party = 27, CPartied = 18, Email = "jennie@blackpink.com", SDate = DateTime.Parse("2021-06-27"), EDate = DateTime.Now.AddDays(12), OPrice = 54800, SPrice = 22000, Contents = "게임하자!", SellStat = 0 },
        new() { UserId = "sunminnie", Category = "g", Title = "Mass Effect Legendary Edition", Party = 46, CPartied = 46, Email = "rosie@blackpink.com", SDate = DateTime.Parse("2021-04-18"), EDate = DateTime.Now.AddDays(-9), OPrice = 66000, SPrice = 24000, Contents = "게임하자!", SellStat = 1 },
        new() { UserId = "lawhope", Category = "g", Title = "Assasin's Creed Valhalla", Party = 44, CPartied = 44, Email = "tan@madmonster.com", SDate = DateTime.Parse("2021-06-04"), EDate = DateTime.Now.AddDays(-4), OPrice = 65900, SPrice = 19000, Contents = "게임하자!", SellStat = 1 },
        new() { UserId = "joh4eva", Category = "g", Title = "Biomutant", Party = 10, CPartied = 4, Email = "ikjoonlee@yoolje.com", SDate = DateTime.Parse("2021-06-23"), EDate = DateTime.Now.AddDays(8), OPrice = 64900, SPrice = 28000, Contents = "게임하자!", SellStat = 0 },
        new() { UserId = "goldenmaknae", Category = "g", Title = "Warhammer Storm Ground", Party = 28, CPartied = 12, Email = "dhn9@dam.net", SDate = DateTime.Parse("2021-06-16"), EDate = DateTime.Now.AddDays(6), OPrice = 44800, SPrice = 17000, Contents = "게임하자!", SellStat = 0 },
        new() { UserId = "jayhohoho", Category = "g", Title = "Days Gone", Party = 31, CPartied = 31, Email = "jhs1111@homail.com", SDate = DateTime.Parse("2020-10-16"), EDate = DateTime.Now.AddDays(-35), OPrice = 58800, SPrice = 26000, Contents = "게임하자!", SellStat = 1 },
        new() { UserId = "flowersonghwa", Category = "g", Title = "Ratchet & Clank: Rift Apart", Party = 52, CPartied = 52, Email = "sjlee@natee.com", SDate = DateTime.Parse("2021-05-07"), EDate = DateTime.Now.AddDays(-7), OPrice = 79800, SPrice = 40000, Contents = "게임하자!", SellStat = 1 },
        new() { UserId = "sunminnie", Category = "g", Title = "Returnal", Party = 22, CPartied = 22, Email = "worldno1@bts.co.kr", SDate = DateTime.Parse("2021-03-06"), EDate = DateTime.Now.AddDays(-19), OPrice = 79800, SPrice = 29000, Contents = "게임하자!", SellStat = 1 },
        new() { UserId = "lawhope", Category = "g", Title = "Godfall", Party = 40, CPartied = 37, Email = "wwhandsome@bts.co.kr", SDate = DateTime.Parse("2021-06-23"), EDate = DateTime.Now.AddDays(4), OPrice = 77800, SPrice = 35000, Contents = "게임하자!", SellStat = 0 },
        new() { UserId = "joh4eva", Category = "g", Title = "New World", Party = 57, CPartied = 14, Email = "jennie@blackpink.com", SDate = DateTime.Parse("2021-06-23"), EDate = DateTime.Now.AddDays(15), OPrice = 41000, SPrice = 15000, Contents = "게임하자!", SellStat = 0 },
        new() { UserId = "goldenmaknae", Category = "g", Title = "BattleField 2042", Party = 11, CPartied = 11, Email = "rosie@blackpink.com", SDate = DateTime.Parse("2021-05-06"), EDate = DateTime.Now.AddDays(-8), OPrice = 66000, SPrice = 34000, Contents = "게임하자!", SellStat = 1 },
        new() { UserId = "jayhohoho", Category = "g", Title = "Mario Golf: Super Rush", Party = 25, CPartied = 25, Email = "tan@madmonster.com", SDate = DateTime.Parse("2021-05-04"), EDate = DateTime.Now.AddDays(-10), OPrice = 64800, SPrice = 29000, Contents = "게임하자!", SellStat = 1 },
        new() { UserId = "flowersonghwa", Category = "g", Title = "F1 2021 Deluxe Edition", Party = 47, CPartied = 47, Email = "ikjoonlee@yoolje.com", SDate = DateTime.Parse("2020-10-06"), EDate = DateTime.Now.AddDays(-40), OPrice = 83000, SPrice = 47000, Contents = "게임하자!", SellStat = 1 },

        // Utility (u)
        new() { UserId = "sunminnie", Category = "u", Title = "경리나라", Party = 60, CPartied = 60, Email = "dhn9@dam.net", SDate = DateTime.Parse("2021-05-03"), EDate = DateTime.Now.AddDays(-6), OPrice = 900000, SPrice = 657000, Contents = "유틸 쓰자!", SellStat = 1 },
        new() { UserId = "lawhope", Category = "u", Title = "얼마에요", Party = 15, CPartied = 13, Email = "jhs1111@homail.com", SDate = DateTime.Parse("2021-06-30"), EDate = DateTime.Now.AddDays(18), OPrice = 35000, SPrice = 12200, Contents = "유틸 쓰자!", SellStat = 0 },
        new() { UserId = "joh4eva", Category = "u", Title = "ecount", Party = 39, CPartied = 39, Email = "sjlee@natee.com", SDate = DateTime.Parse("2021-04-07"), EDate = DateTime.Now.AddDays(-12), OPrice = 40000, SPrice = 23000, Contents = "유틸 쓰자!", SellStat = 1 },
        new() { UserId = "goldenmaknae", Category = "u", Title = "BigTime", Party = 29, CPartied = 29, Email = "worldno1@bts.co.kr", SDate = DateTime.Parse("2021-06-04"), EDate = DateTime.Now.AddDays(-5), OPrice = 34000, SPrice = 16000, Contents = "유틸 쓰자!", SellStat = 1 },
        new() { UserId = "jayhohoho", Category = "u", Title = "precoro", Party = 47, CPartied = 39, Email = "wwhandsome@bts.co.kr", SDate = DateTime.Parse("2021-06-23"), EDate = DateTime.Now.AddDays(2), OPrice = 22000, SPrice = 9600, Contents = "유틸 쓰자!", SellStat = 0 },
        new() { UserId = "flowersonghwa", Category = "u", Title = "한글오피스", Party = 60, CPartied = 60, Email = "jennie@blackpink.com", SDate = DateTime.Parse("2020-11-06"), EDate = DateTime.Now.AddDays(-45), OPrice = 63800, SPrice = 29000, Contents = "유틸 쓰자!", SellStat = 1 },
        new() { UserId = "sunminnie", Category = "u", Title = "Luminar", Party = 42, CPartied = 42, Email = "rosie@blackpink.com", SDate = DateTime.Parse("2021-05-25"), EDate = DateTime.Now.AddDays(-3), OPrice = 129000, SPrice = 90000, Contents = "유틸 쓰자!", SellStat = 1 },
        new() { UserId = "lawhope", Category = "u", Title = "MAYA", Party = 40, CPartied = 24, Email = "tan@madmonster.com", SDate = DateTime.Parse("2021-06-15"), EDate = DateTime.Now.AddDays(9), OPrice = 27500, SPrice = 13000, Contents = "유틸 쓰자!", SellStat = 0 },
        new() { UserId = "joh4eva", Category = "u", Title = "Revit", Party = 41, CPartied = 20, Email = "ikjoonlee@yoolje.com", SDate = DateTime.Parse("2021-05-25"), EDate = DateTime.Now.AddDays(11), OPrice = 250000, SPrice = 170000, Contents = "유틸 쓰자!", SellStat = 0 },
        new() { UserId = "goldenmaknae", Category = "u", Title = "Hand Draw", Party = 29, CPartied = 29, Email = "dhn9@dam.net", SDate = DateTime.Parse("2021-06-25"), EDate = DateTime.Now.AddDays(-2), OPrice = 3700, SPrice = 2000, Contents = "유틸 쓰자!", SellStat = 1 },
        new() { UserId = "jayhohoho", Category = "u", Title = "Pose Tool", Party = 37, CPartied = 37, Email = "jhs1111@homail.com", SDate = DateTime.Parse("2021-06-13"), EDate = DateTime.Now.AddDays(-4), OPrice = 8500, SPrice = 5000, Contents = "유틸 쓰자!", SellStat = 1 },
        new() { UserId = "flowersonghwa", Category = "u", Title = "PicsArt", Party = 26, CPartied = 19, Email = "sjlee@natee.com", SDate = DateTime.Parse("2021-07-01"), EDate = DateTime.Now.AddDays(7), OPrice = 27000, SPrice = 12000, Contents = "유틸 쓰자!", SellStat = 0 },
    };
    context.Products.AddRange(products);
    context.SaveChanges();
}
